# Publish the Docker image to GitHub Docker Registry
name: Docker build & publish

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Image IDs
        id: image_id
        run: |
          echo "::set-output name=full_id::$(git describe --tags --abbrev=0)-$(git rev-parse --abbrev-ref HEAD)"
          echo "::set-output name=short_id::$(git describe --tags --abbrev=0)"
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/user/app:latest
            ghcr.io/user/app:${{ steps.image_id.outputs.full_id }}
            ghcr.io/user/app:${{ steps.image_id.outputs.short_id }}